version: '3'

services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    profiles:
      - prod
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.letsencrypt.acme.email=<email>"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      # this line is only for test purpose - set domain and run once, if traefik logs show no problem then disable
      # look https://letsencrypt.org/docs/rate-limits/
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cakecdn:latest
    profiles:
      - demo
      - prod
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cake.tls=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.cake.rule=Host(`<domain>`)"
      - "traefik.http.routers.cake.entrypoints=websecure"
      - "traefik.http.routers.cake.tls.certresolver=letsencrypt"

    depends_on:
      - db
      - s3
    environment:
      - SPRING_DATASOURCE_USERNAME=cake
      - SPRING_DATASOURCE_PASSWORD=UUcm3K4nT3MEFRmfRMj4
      - MINIO_CREDENTIALS_ACCESSKEY=cake
      - MINIO_CREDENTIALS_SECRETKEY=sbmKVeCWHwd4fxbMqwuY
    networks:
      - traefik_net
      - cake_net


  db:
    image: postgres:16.1-alpine3.18
    restart: unless-stopped
    profiles:
      - local
      - demo
      - prod
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=UUcm3K4nT3MEFRmfRMj4
      - POSTGRES_USER=cake
      - POSTGRES_DB=cakecdn_db
    networks:
      - cake_net

  s3:
    image: minio/minio
    restart: unless-stopped
    profiles:
      - local
      - demo
      - prod
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_volume:/data
    environment:
      MINIO_ROOT_USER: cake
      MINIO_ROOT_PASSWORD: sbmKVeCWHwd4fxbMqwuY
    command: server --console-address ":9001" /data
    networks:
      - cake_net
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.cake.tls=true"
      - "traefik.docker.network=traefik_net"
      - "traefik.http.routers.cake.rule=Host(`<domain>`) && PathPrefix(`/minio`)"
      - "traefik.http.routers.cake.entrypoints=websecure"
      - "traefik.http.routers.cake.tls.certresolver=letsencrypt"

volumes:
  s3_volume:
  db_volume:

networks:
  # if you already have traefik, rename and set external: true
  traefik_net:
    external: false
  cake_net:
    external: false
