spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5000KB
      max-request-size: 5000KB
  datasource:
    url: jdbc:postgresql://localhost:5432/cakecdn_db
    username: cake
    password: UUcm3K4nT3MEFRmfRMj4

minio:
  enabled: true
  endpoint: http://localhost:9000
  credentials:
    accessKey: cakecdn
    secretKey: sbmKVeCWHwd4fxbMqwuY
